version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: 
          name: prepare environment
          working_directory: /go/src/github.com/skhedim/demo-gitops  
          cp ~/project/app/* .
          go get -u github.com/golang/dep/cmd/dep
      - run:
          name: run build
          command: |
            dep init -v
            go build -v
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: Build and push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t ${DOCKER_REPO}:{CIRCLE_BUILD_NUM} .
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} https://index.docker.io/v1/                                                 
              docker push ${DOCKER_REPO}:{CIRCLE_BUILD_NUM}
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master