version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: 
          name: Prepare build environment
          command: |
            mkdir -p /go/src/github.com/skhedim/demo-gitops
            cp ~/project/app/* /go/src/github.com/skhedim/demo-gitops
            go get -u github.com/golang/dep/cmd/dep
      - run:
          name: run build
          working_directory: /go/src/github.com/skhedim/demo-gitops
          command: |
            dep init -v
            go build -o ~/project/docker -v
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build and push Docker image
          working_directory: ~/project/docker
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t ${DOCKER_REPO}:${CIRCLE_BUILD_NUM} .
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} https://index.docker.io/v1/                                                 
              docker push ${DOCKER_REPO}:${CIRCLE_BUILD_NUM}
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master