{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "regcred",
    "namespace": "gitops-demo",
    "creationTimestamp": null
  },
  "spec": {
    "data": "AgARcDSz9SvnaaTQCVTu/kXge68KduQwpzxnoSrVBVno8RKe4tM8hKlHv5ozzSpqYThCrl6dfkTJ193sQqsXYmVqsk3ajfOAzL10H0lYM6JdoOjZfjAJceJkYWpyO1UZVTcTLVIMZjE3K/lTGfpy7svuqhxbY1dhoq0G1itvisg0oziooz8ClbH2gDOoi+5r6p3NB59UqfjtehjV5jVEZNpEhbVMybvgzEE2nPjoOFU+ZUz3yejmTpcsrd/nBsR2hhb2TPSLSODYhtVfsbjgWjuHzMwO83FC3VcHBxEsEambplxOo0LzbNdlkezpl+gKwlJa6OFV4y6lcamfelY08LN9wi4q5M9/GKFuptEI4Y1JmqY0hCsOEf9bnMwBRg7mTmEUGT8AE5ermNvZHMETRLgZejBNZtHm/LH5cPczTdpUl+GejWVxqD6eR2gxo/g2kU+jNfBCtD+1EFdeAay2T4TtFI8uSNyah2dlUjpUSBQPmphT0d048XY0FyvoF1GEguDpjdLq2TFUQYAzgVyR4z2ZGiH7paLV/QKx8z9Zvv6agtIRjfOyFSS1jTAvWsok1Aq/oiXaP6pt5sKSczknUisllpps25onQ2Pn2p7Op8rYI/vY+jLNsCeuPk/Ji7tGFk2ZmWmNafMCQcIInQDdMQ7AHHGv7IWlipjCzHd1zfKvXYwPCF+A5zAFdXaj/Q7K1iz4o9GxyJggYic5Kqumpl6+Ug1DRx3Cvz9x1lb+md50sTbMmrYShEqlC0WmkiXj35hxmA3uZk4V+wuI0rPpc+8Jv1WrJ7/0z5tTeOHbPB0hiR+nou9YaZ2Om/40q4BzdPWOXkZKuW2jbe2o3hyR5jcwol7p7FPyh6LbitEzMiifSv5l1ovKV9ssJy9YbVNQWZVIt/AEd2H4DsfCPjHYX8/52XL0FRV2QvNlwWQXRcRNBAKo9ojI8V1ba7ZSMMRrK5J1LnboScof9JgVZ5LJp20MreiWfGBzEbroA/D6oYjHWtpMpOoK47QEflgLKvbzEDZ1kEZfx+bGLAYv/EtF6I+ufyGGVbR9ARupVTVSHK6XvjBq0z1hNxdd/TsGmQFZvau962Ker3IMRBxYrJ7M7xb4wo8Y44E+zASTjvloskBOvycdjly+5zbK9vY/JO9qDU9Lqm+QjyXMlFx37ssQPcT+FGhCkfgpFagbvxv1GXdznW8+xKcLQiOSazhvEPBl3FL1pOlWvmKJ63vmNsYR98b0MA=="
  }
}
